[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "C153Jyim6dDSPeLMHFQe3LTPrhPXLVr16Cz5rPEeKvrJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
